### ISSUE TITLE
Stuck on start

### ISSUE THREAD

**Issue by Scruffeyis** [anthonyraymond/joal-desktop#10]
@anthonyraymond 

As mentioned by a couple other people, Joal gets stuck on running. It successfully booted once but has failed since. I have tried following this `Could you also try to:
Quit the app (completly)
Remove ~/Library/Application Support/JoalDesktop/jre directory
Remove ~/Library/Application Support/JoalDesktop/joal-core directory
Restart the app`
I have also tried deleting the Application Support folder entirely and restarting the app which also does not work.
I have emailed the address from one of the issues with the debug script results.
<img width="1136" alt="Screenshot 2019-09-23 at 17 05 50" src="https://user-images.githubusercontent.com/55707281/65442892-eb564800-de24-11e9-847b-e7e9c46d8768.png">

Thanks,
J
OS: Mac OS Catalina Version 10.15 Beta

**Comment by 0TerenceTerence0** [comment]
I have exactly the same issue. 

Os: Mojave 10.14.6

**Comment by anthonyraymond** [comment]
@Scruffeyis Thanks for the email log report :)

While the script is started, what do you have when you go to : http://localhost:5081/aaaaa/ui/ in a browser? Do you find the joal webui (even if it says "failed to connect")

**Comment by plozachm** [comment]
This site can’t be reachedlocalhost refused to connect.
Search Google for localhost 5081 aaaaa
ERR_CONNECTION_REFUSED

**Comment by anthonyraymond** [comment]
Hi,

i'm actually rewriting the whole tool in a new language (`golang`). That will help improving joal performance a lot (something like *10 at least). And hopefully fix this crap that happens on macOS.

I'll publish an update when the new version will be over and properly tested, so far the proejct is hosted as a private repository no to confuse everybody with a new joal repository.

**Comment by theociet19** [comment]
Hi Anthonyraymond,

The Mac OS version of JOAL is still not working at the moment. Do you know when the update will be released?

Thank you for your help!

**Comment by anthonyraymond** [comment]
Hi in the next few month probably, it takes some time to completly recode the whole project in another language.
But there is a workaround here: https://github.com/anthonyraymond/joal-desktop/issues/13#issuecomment-556944021
