### ISSUE TITLE
What executable is joal using to connect to the torrent tracker?

### ISSUE THREAD

**Issue by dxdvostfr** [anthonyraymond/joal-desktop#100]
I live in an country where where running torrents witout a vpn will get you legal trouble.

I can't seem to make the joal torrent traffic go through my vpn, no matter what executable I put into my torrent tunnelling. I tried AppData\Local\Programs\joal-desktop\joaldesktop.exe, AppData\Roaming\JoalDesktop\jre\bin\java.exe, and the system32/conhost.exe (so all the executables joal was running on my machine), yet my torrent traffic is still being pushed via my regular ip.

Could I know of wich executable the joal traffic is coming from? Thanks!

**Comment by anthonyraymond** [comment]
Hello,

Well, it is a java executable jar that runs, i'm not sure what you should target to get the trafic though your VPN.
Maybe `AppData\Roaming\JoalDesktop\core\joal-core\jack-of-all-trades.xxxxx.jar`.

But i'm not sure how to achieve this for sure.
