### ISSUE TITLE
Impossible to launch GUI Joal on MAC OS

### ISSUE THREAD

**Issue by foch01** [anthonyraymond/joal-desktop#101]
I opened and closed the JOAL mistletoe a few times today (3 to 4 times).

But after the 4th time I am stuck on this screen.

<img width="1024" alt="image" src="https://github.com/anthonyraymond/joal-desktop/assets/19187357/e440e468-58fb-4550-bc86-f57095b470b4">

Do you have an idea of ​​the issue ?

**Comment by anthonyraymond** [comment]
Can you take a look at this post and tell me if it works? #13

**Comment by foch01** [comment]
Yes it's good thanks :)
