### ISSUE TITLE
App stucked after Updates Checking

### ISSUE THREAD

**Issue by JoalEnjoy** [anthonyraymond/joal-desktop#107]
I have managed to run the app the first time on MacOS. But since then, every time I open it it checks for update and then it never launches the app.  I have tried to reinstall several times but did not work.

**Comment by Gh0st113** [comment]
Hi same issue on windows 11 i try to reinstall and nothing

**Comment by anthonyraymond** [comment]
Should be related to: https://github.com/anthonyraymond/joal-desktop/issues/13

have a try
