### ISSUE TITLE
Is it still considered "active" if I set the minimum and maximum upload speeds to 0?

### ISSUE THREAD

**Issue by cramberries** [anthonyraymond/joal-desktop#113]
Hello. New user here.

Very recently had my dedicated seeding drive fail and I don't think I can replace it any time soon. Found this amazing tool and desperate enough to try it out but I'm not looking to spoof my ratio. I'm a bit too paranoid about that for now. Lol. But I do want to continue increasing my seedtime for the torrents I have been seeding until I can buy a new drive.

I currently have a torrent loaded from a public tracker to test it and my settings are set to 0 minimum and maximum upload speed. But in the dashboard, it shows `Torrents in queue: 0` which makes me think it's not considered as currently active?

Again, since I just found out about this a couple of hours ago, I'm still a bit paranoid. So not personally ready to test it on an actual private tracker torrent yet. I hope it's okay to ask this here. Thank you.

I'll add photos of my dashboard and settings below:

![image](https://github.com/user-attachments/assets/9a04e8df-476b-4053-9899-b67fcfe2227d)
![image](https://github.com/user-attachments/assets/b294f0eb-cdbd-45ab-b751-d775684d5e17)

**Comment by anthonyraymond** [comment]
Hello, cramberries,

First, your setup is perfectly fine. Having a zeroed max speed is fine to
use.

The "queued torrents" will start to increase if you had more torrent than
the "simultaneous seed" config. Queued torrents are basically in queue,
inactive.

When you'll start using it on real tracker please adapt the "torrent
client" config to latch you real client. You don't need to match the exact
same version but at least match the client (qbittorrent, utorrent, ...)

**Comment by cramberries** [comment]
@anthonyraymond 
Thank you so much for the quick response and I apologise for the delay of mine. After reading your reply, I decided to test it on a general tracker I'm in but it only updates every 30 minutes so I decided to wait until then before responding. I can confirm it is working great for me and it's counting up the seed time without increasing my upload.

Thank you so much for creating this tool. Now, I just feel a little dumb for misunderstanding what "queue" meant. Lol. Thank you again!

**Comment by cramberries** [comment]
@anthonyraymond
I hope you don't mind me coming back in and just asking this question in this thread. But would it be possible to set a specific port? I cannot see anything in the settings for that.

I have a particular one that I use for a specific private tracker and it hasn't changed in years so that might be noticeable if moderators are checking that sort of thing. Thank you again!

**Comment by anthonyraymond** [comment]
It is not yet possible, but i'm thinking about writing another version from scartch.
It will be on the feature list for the rewrite

**Comment by cramberries** [comment]
@anthonyraymond
Thank you. I was looking at the main JOAL repo and saw there's info for specifying the port so I thought this would have one as well. But I couldn't ID a file that looks like a config file in the directory so I asked.

Sorry for bothering you about it but I'm looking forward to the next iteration. Thank you!
