### ISSUE TITLE
Upload speed 0 

### ISSUE THREAD

**Issue by slashjim** [anthonyraymond/joal-desktop#14]
Hi
I'm running the app on MacOS and the upload speed is stuck at 0. 
I've added several torrent files, some with a lot of leechers and some few but still stuck at 0 
I've tried to check : "http://localhost:5081/aaaaa/ui/ abut" I got "ERR_EMPTY_RESPONSE"

**Comment by anthonyraymond** [comment]
Can you list the number of leechers / seeders that joal show for every torrents please?

**Comment by slashjim** [comment]
It gives 0 leechers and 0 seeders for every torrent.

**Comment by anthonyraymond** [comment]
It may be your tracker who does not follow the bittorret spécifications properly.
There is nothing i can do about that for now

Le 11 déc. 2019 à 16:41, à 16:41, slashjim <notifications@github.com> a écrit:
