### ISSUE TITLE
Torrents automatically disconnects

### ISSUE THREAD

**Issue by nordzlos** [anthonyraymond/joal-desktop#22]
The torrents automatically disconnects after 1h or so from the time the program starts and do not list as connected on trackers even though the program is open.

**Comment by anthonyraymond** [comment]
Hi @nordzlos,

Can you answer some questions so i can help you a little bit further:
 -  what version of Joal-Desktop are you using?
 - On which OS?
 - What do you mean by "disconnects" do they disapear from joal or do they stay in joal but produce no more seed on the tracker view?

**Comment by bertasse** [comment]
Good morning to both of you and everyone. I hope my English will not be too bad. I have the same problem as nordzlos. After an hour of use, my torrents disappear from the JOAL screen. It's empty and I have no transfers. I am on W10 with JOAL version 2.0.2. Thanks for your help .... Pascal

![2020-05-12 18_50_50-JOAL ui](https://user-images.githubusercontent.com/38837469/81722609-e8769900-9481-11ea-9429-46ef23bd3f88.jpg)

**Comment by bertasse** [comment]
![2020-05-12 19_02_18-JOAL ui](https://user-images.githubusercontent.com/38837469/81723480-2d4eff80-9483-11ea-9314-7380a0c93eed.jpg)

**Comment by anthonyraymond** [comment]
Thanks to @CoderCore i've identified and fixed a but that occurs when the tracker start to be weird and a bit buggy about http request. (https://github.com/anthonyraymond/joal/issues/98)
A new release is compiling and should be available by tomoring (depending on the build time on both travis & appveyor)

**Comment by anthonyraymond** [comment]
Update is available.
