### ISSUE TITLE
Fixed values for the upload

### ISSUE THREAD

**Issue by nordzlos** [anthonyraymond/joal-desktop#23]
since two or three days ago or so, the values for the upload are fixed like, it stays at a number and never changes as for the norm it would change the values like 100kbps, to 99.1kbps to 110kbps goes back to 100.3kbps, to seem like a real seeder and after awhile the tracker stops listing as online even though there are leechers on the particular torrents. Not sure if it's a bug or something else.

**Comment by anthonyraymond** [comment]
That looks weird indeed, the value is supposed to change at least every 30 to 40 minutes. Does it resove the issue if you restart completly Joal-Desktop? Which OS are you on?

**Comment by nordzlos** [comment]
Windows 10, it was working fine as of last week but recently started showing up these problems, trying to downgrade wasn't able to, tried to uninstall, deleted %appdata% files, still the same error.

**Comment by nordzlos** [comment]
also noticed it keep alive whenever the number in queue is the total number of all torrents but negative otherwise it kills the connection.

**Comment by anthonyraymond** [comment]
What version of joal are you using? (if you don't know you can get all the details from the Help>About menu.

![image](https://user-images.githubusercontent.com/7503585/84781267-e9519c00-afe6-11ea-9553-e353b38453a8.png)

Also, can you share a screenshot of the whole JOAL UI?

**Comment by nordzlos** [comment]
https://images2.imgbox.com/bf/84/Te1nABrx_o.jpg
