### ISSUE TITLE
[Feature Request] Refresh announcement / manual announcement 

### ISSUE THREAD

**Issue by nordzlos** [anthonyraymond/joal-desktop#25]
Could you add a button for manual announce update the tracker? What I am requesting is a button where when you click it will manually re-announce all torrents added, if possible, thanks!

**Comment by anthonyraymond** [comment]
Hello,

That's not something i'll add to JOAL for security reasons. Random announces are not something that could occur in real client. Plus by experience i know that: if there is a button, people usually click on it (too much).

Such a feature would sounds like "click to update" for most people but it makes the client really suspicious from a tracker point of view.

If you concerns is to update before closing the app, just press the "STOP" button and wait for all the torrent to disappear. When a torrent is stopped it announces itself to the tracker to report that it is going away. So your stats are updated at the time.
