### ISSUE TITLE
Torrents keep disappearing even though "Keep seeding torrents even with no peers" is checked

### ISSUE THREAD

**Issue by krully37** [anthonyraymond/joal-desktop#28]
Using torrents from a rather popular french tracker they keep disappearing after a few days to a few weeks even though "Keep seeding torrents even with no peers" is checked. Last torrent I checked had no leechers so maybe the function isn't working as intended and still stops seeding when noone is leeching?

**Comment by anthonyraymond** [comment]
Hi,
What version are you using? Joal or joal desktop.
If you are using torrent from yggtorrent they recently changes their tracker domain name so you need to redownload all the .torrent from the new domain.

Le 9 août 2020 à 13:32, à 13:32, krully37 <notifications@github.com> a écrit:

**Comment by krully37** [comment]
Joal Desktop 2.0.3

It is possible it happens depending on domain changes, I will keep an eye on that and will reopen a ticket if it's a different issue than that. Thank you.
