### ISSUE TITLE
Stucks on start 2.0.3 on windows 10

### ISSUE THREAD

**Issue by fredfred41** [anthonyraymond/joal-desktop#29]
Desktop App---Ok

Joal Core ------Ok

Java runtime environnement --Ok

But it stop here, on the "checking for update" screen

I already tried to quit the app, remove \AppData\Roaming\JoalDesktop\jre directory and remove \AppData\Roaming\JoalDesktop\joal-core directory

Runnig Windows 10 19041.450 but problem happen before latest update too

Tell me what you need, if I could help to investigate on this, 

Thanks

**Comment by anthonyraymond** [comment]
Does it still stays stuck after a ful reboot ?

**Comment by fredfred41** [comment]
today, it s working ?!!? 
Don't know why...
Maybe because I restart my computer since last time I deleted  \AppData\Roaming\JoalDesktop\jre and \AppData\Roaming\JoalDesktop\joal-core directory...
Will try next time the app block...

**Comment by anthonyraymond** [comment]
Great, feel free to re-open the issue if it happens again
