### ISSUE TITLE
Transmission 2.93 addition

### ISSUE THREAD

**Issue by jamiehaywood** [anthonyraymond/joal-desktop#3]
Transmission have recently updated their latest version to 2.93. Are you able to update the version in Joal?

**Comment by anthonyraymond** [comment]
Hi @jamiehaywood, sorry for the delay.

A new update is coming soon (one or two days) with these four new clients:
- uTorrent 3.5.3 (build 44358)
- BitTorrent 7.10.3 (build 44359)
- Transmission 2.93
- qBittorrent 4.0.4

Thanks for notifying about the new transmission update 👍

**Comment by anthonyraymond** [comment]
Builds waere faster than usual  on Travis 😄 
Update is available right now
