### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by humarkx** [anthonyraymond/joal-desktop#36]
https://prnt.sc/vz0xwm

**Comment by anthonyraymond** [comment]
Os? When did that happened?

**Comment by humarkx** [comment]
This error happens on **Version 2.0.5** with MacOS Big Sur 11.0.1 (20B29)

Version 2.0.4 works fine.

**Comment by anthonyraymond** [comment]
Can you try again?
i applied a temporary fix until 2.0.6 gets released

**Comment by anthonyraymond** [comment]
Problem solved
