### ISSUE TITLE
Error when adding torrent: STOMP 'CONTENT-LENGTH' HEADER VALUE 6650509 EXCEEDS CONFIGURED BUFFER SIZE LIMIT 5120000

### ISSUE THREAD

**Issue by Paradoxpm** [anthonyraymond/joal-desktop#39]
Error "STOMP 'CONTENT-LENGTH' HEADER VALUE 6650509 EXCEEDS CONFIGURED BUFFER SIZE LIMIT 5120000" when adding a large torrent file. Maybe increase buffer size limit?

**Comment by anthonyraymond** [comment]
Hello,
It happens when you try to add a very big tirrent file. Atm there is nothing you can do (other than putting the file in the folder mnually).

In the next version this problem will be solved :)

Le 27 janv. 2021 à 12:52, à 12:52, Paradoxpm <notifications@github.com> a écrit:
