### ISSUE TITLE
Issues on mac version

### ISSUE THREAD

**Issue by Tzeenn** [anthonyraymond/joal-desktop#49]
Sorry by advance for my approximative explanation of the issue, I am far from being an expert on such things...

I downloaded Joal in order to keep a stable ratio on Ygg using utorrent web. However, so far, nothing changed after using Joal, and I don't know which important step I have missed when installing/running the program :) Here is what I did:

1) Download of the torrent file
2) Download of JoalDesktop-2.0.6-mac.dmg
3) Before I understood Joal was uploading and not downloading, I dragged and dropped the torrent file in Joal, but of course that didn't change anything.
4) I then opened the torrent file with utorrent web. When the download was completed, I deleted the torrent from utorrent (but kept the downloaded files on my laptop)
5) I closed utorrent web and re-opened Joal, where I dropped again the torrent file. But still, nothing happened.

It appears that the torrent has no peers, because when I unclick the "keep seeding even with no peers", the torrent disappears. Otherwise, it stays in the queue, but the speed is 0 B/s. However, I do not really understand what "having no peers" mean, and why this is the case. On Ygg, the torrent has 21 Seeders and 0 Leechers.

Thank you for your help!!

**Comment by anthonyraymond** [comment]
Hello,

Torrents needs to have at least 1 seeder **and** 1 leechers, otherwise it won't do anything
