### ISSUE TITLE
Mac Problem

### ISSUE THREAD

**Issue by apartmandairesi** [anthonyraymond/joal-desktop#50]
Hi.

I'm using Joal for MacOs version. Everything works well until 2 days before. When I open Joal, it not go on and look like this

<img width="789" alt="Screenshot at May 17 11-48-58" src="https://user-images.githubusercontent.com/84267564/118461083-f77fcf00-b705-11eb-94c7-41cefd568b10.png">

I deleted app, re-installed but same thing goes on. Do you have any idea?

Thanks.

Edit: Screenshot

**Comment by anthonyraymond** [comment]
Hello,

take a look at : https://github.com/anthonyraymond/joal-desktop/issues/13
