### ISSUE TITLE
Java runtime Environnement error undefined

### ISSUE THREAD

**Issue by jencerien** [anthonyraymond/joal-desktop#52]
Hello,

I used Joal since months and I love it. 
Now I tried to install Joal Desktop on a new computer and the application refuses to start, because of java. On Windows 10.
Java is up-to-date. I have the same problem on Mac (Big Sur and older one)

What could I do ?

Best
![image](https://user-images.githubusercontent.com/86256832/125437314-fb48c74e-971f-453b-89f0-3a2a0df0d5c5.png)

**Comment by ronioncloud** [comment]
same here after reinstall

**Comment by Kenddriz** [comment]
same here
Did someone find the solution ?

**Comment by anthonyraymond** [comment]
Hello there, thanks for the report and the troubleshoot.

I think i know how to fix that, i'll take a look at it asap :)

**Comment by anthonyraymond** [comment]
A quick feedback:

I'm on it, but i need to transform all of the old travis CI build system to Gitlab Actions, i've spent 3 hours transforming the joal-core one ^^.
Next to come : joal-ui & joal-desktop. Should be Ok in the next few day (maybe next week)

**Comment by anthonyraymond** [comment]
Ok, it's now done, you just need to update your client and it should work as expected.

(if you are on windows juste restart JoalDesktop to automatically download the new version 2.0.7)
