### ISSUE TITLE
Stucks on start on windows 11

### ISSUE THREAD

**Issue by wloot** [anthonyraymond/joal-desktop#56]
It is not working anymore since i upgrade os to windows 11.

I've tried reinstall and delete data dir, both are no help.

**Comment by anthonyraymond** [comment]
Well.. i'm afraid i won't be of any help ATM. Windows  is still in beta so it might come from JOAL or Windows.

Plus i does not have an access to W11 ATM. I'll look at it as soon as W11 get publicly released.
