### ISSUE TITLE
the mac app get stuck in the first page

### ISSUE THREAD

**Issue by mahmoud200m** [anthonyraymond/joal-desktop#7]
The mac version get stuck in the first page after finish checking the updates (very rare times it continue to the next screen after a while)

<img width="1091" alt="Screenshot 2019-03-18 at 5 33 20 PM" src="https://user-images.githubusercontent.com/11187803/54546619-56215500-49a4-11e9-8f85-da528e0a9e6d.png">

OS: macOS Mojave 10.14.3

**Comment by Xneo78** [comment]
Hi
Exactly the same issue since a few weeks on macOS High Sierra 10.13.4.

**Comment by anthonyraymond** [comment]
Hi, i known what this is about, but this solution is not as simpel as that, plus i'll need to get my hands on a MAC, I'm working on it but i'll need some time :)

**Comment by Xneo78** [comment]
thanks for your consideration :)

**Comment by anthonyraymond** [comment]
Could you try to leave the app open for like 4 or 5 minutes on the stucked screen and see what happens? If it does not works i'll send you a script to start the app in cole more (for debuging purpose on macos)

**Comment by Xneo78** [comment]
In my case, I do not spend the screen even after several hours on the page. The problem appeared a few weeks ago, it worked very well before.

**Comment by anthonyraymond** [comment]
Ok, thats great, i'll send you a script asap to diagnose joal. Are you confortable with terminal and bash scripts?
Will you be able to run it or will you need some guidance?

**Comment by Xneo78** [comment]
No problem, I work on Unix systems :)

**Comment by Xneo78** [comment]
Thanx a lot for your help

**Comment by anthonyraymond** [comment]
Nice 😄 

[Here is the script](https://github.com/anthonyraymond/joal-desktop/blob/master/debug-scripts/joal-desktop-debug.macos.sh)

I've not tested it myself, but i believe it should work. No need to mess with the terminal location, it will find his way to joal.

Start joal desktop and be sure that it still does not boot properly. Then close JoalDesktop and start this script, then let me know what you get :)

Be carefull when pasting your log to github, it may contains passkey, your ip or even some more private informations. If you want you can send the log to `joal.contact@gmail.com`

**Comment by 0TerenceTerence0** [comment]
Hello! 
I have the same issue. 
I don't know if it'll help, but here what i get when i run the script in terminal : 

> [INFO ] 2019-06-15 12:02:30.417 [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats: WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannelpool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]

**Comment by anthonyraymond** [comment]
There should be plenty of stuff before that ^^ can you mail it to me at joal.contact@gmail.com please?
There should be at least one error and maybe a call stack in the log

**Comment by anthonyraymond** [comment]
Could you also try to:

- Quit the app (completly)
- Remove `~/Library/Application Support/JoalDesktop/jre` directory
- Remove `~/Library/Application Support/JoalDesktop/joal-core` directory
- Restart the app

**Comment by fgladu** [comment]
In my case, when it happens, a full restart is necessary...
Mac Mini mid 2011 macOS 10.13.6.

**Comment by anthonyraymond** [comment]
Hi, There is a workaround here, take it a look: https://github.com/anthonyraymond/joal-desktop/issues/13#issuecomment-556944021

That's not the definitive solution but it will help solve the issue until the new version is release in the next few months
