### ISSUE TITLE
Can I use it on my vps

### ISSUE THREAD

**Issue by oyuntuayC** [anthonyraymond/joal-desktop#72]
Hi, I learned about this software from a forum, but I'm not sure how to use it on my VPS.

**Comment by oyuntuayC** [comment]
Im using xserver now

**Comment by anthonyraymond** [comment]
Hello,
Joal desktop is the desktop version of joal.
https://github.com/anthonyraymond/joal

You should take a look at it. The best aproach IMO is to use docker
