### ISSUE TITLE
Can't add a torrent on Windows 11.

### ISSUE THREAD

**Issue by kriki200** [anthonyraymond/joal-desktop#74]
Hi, I can't seem to add a torrent, as every time I do it just starts loading and then it empties the list.

**Comment by malexxx** [comment]
Working great for me With the last joal-desktop on Windows 11.

**Comment by anthonyraymond** [comment]
Torrent are automatically removed when they have 0 leechers IR 0 seeders, you must use active torrent with at least 1 seeder AND 1 leecher
