### ISSUE TITLE
HELP .I NEED HELP!

### ISSUE THREAD

**Issue by user4396** [anthonyraymond/joal-desktop#75]
it seems like the server does not work.win10.

![捕获](https://user-images.githubusercontent.com/102785769/161221041-f7817203-c626-4208-8c03-edc83741e0c8.PNG)

why?

can you help me?

**Comment by user4396** [comment]
the link is picture

**Comment by user4396** [comment]
I have used the proxy,may it is the problem?But I dont Kona how to handle it

**Comment by user4396** [comment]
@anthonyraymond

**Comment by anthonyraymond** [comment]
As for now, JOAL does not support proxy :/ on working on it for the next version
