### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by kriki200** [anthonyraymond/joal-desktop#77]
This does not work on ARM right?

**Comment by anthonyraymond** [comment]
You can't use JoalDesktop on ARM architecture indeed.
But you can use https://github.com/anthonyraymond/joal (it's the server version with optional webui), i recommend to deploy with docker. But it's a little bit trickier to deploy and you'll need some IT skills in order to use it.

**Comment by kriki200** [comment]
> You can't use JoalDesktop on ARM architecture indeed. But you can use https://github.com/anthonyraymond/joal (it's the server version with optional webui), i recommend to deploy with docker. But it's a little bit trickier to deploy and you'll need some IT skills in order to use it.

Thank you, altho if I'll do it I'll do it without Docker, it doesn't seem that hards :) . Also I presume editing the config requires a restart, right?

**Comment by anthonyraymond** [comment]
@kriki200 Yes editing the config file or adding new clients requires a restart
