### ISSUE TITLE
only 5 torrents on dashboard visible

### ISSUE THREAD

**Issue by DmitryZhyvoder** [anthonyraymond/joal-desktop#82]
Only 5 torrents on dashboard visible, even if more than 5 items per page are selected JD 2.0.11

**Comment by anthonyraymond** [comment]
it's working for me.
I think the your setting "Keep torrent with 0 peers" is unticked in the config. And if a torrent has  0 seeder or 0 leecher at any given time it is evicted from the list and move the the /torrents/archived folder.
That's why you only see a subset of torrent.
