### ISSUE TITLE
Illegal Character Error still in 2.0.14

### ISSUE THREAD

**Issue by imswel** [anthonyraymond/joal-desktop#87]
I always got this error when I try to add a torrent from my tracker :

TORRENT WAS REJECTED BY SERVER: JAVA.NET.URISYNTAXEXCEPTION: ILLEGAL CHARACTER IN QUERY AT INDEX 47: HTTPS://XXXXYYYY.ZZZ/ANNOUNCE.PHP?AUTHKEY=11111|22222|AA3BBB

I use joal-desktop 2.0.14

**Comment by butts136** [comment]
I have the same problem as you on one of my trackers.

I'm about to loose my account, There's no leech, so I download 5Go and got almost banned for weeks :P

Thanks

**Comment by anthonyraymond** [comment]
Related to: https://github.com/anthonyraymond/joal-desktop/issues/87
