### ISSUE TITLE
Stuck at startup (2.0.1)

### ISSUE THREAD

**Issue by kazukyakayashi** [anthonyraymond/joal-desktop#9]
Hello,

Joal remains stuck on the start page after the 2.0.1 update.

![joal](http://pix.toile-libre.org/upload/original/1562226910.png)

## Environment

- OS : Antergos (Archlinux).
- Version : AppImage
- Node version : v11.15.0

**Comment by anthonyraymond** [comment]
That is weird, ou'r not the first one to tell me about that issue, but on my gf mac it's working properly, what you can try is:
- Quit the app (completly)
- Remove `~/Library/Application Support/JoalDesktop/jre` directory
- Remove `~/Library/Application Support/JoalDesktop/joal-core` directory
- Restart the app
