### ISSUE TITLE
[BUG] Even if checked, Torrents with 0 peers go in archived

### ISSUE THREAD

**Issue by butts136** [anthonyraymond/joal-desktop#91]
Hi,

The title says everything, Even if the case is checked to keep seeding no peers torrents, it's removing them and sending them into archived folders.

Yes, i have Save the settings and Restart Joal. Yes, i have the last 2.0.16 from today.
It was doing it on the 2.0.15 too.

Thanks

On the screenhot, it's 38 Torrents in 3 minutes because I have But them all back to the torrents folder.

![image](https://user-images.githubusercontent.com/65697898/205210143-28935176-f1e3-486e-825b-36aa8ff88763.png)
![image](https://user-images.githubusercontent.com/65697898/205210244-bb790342-98d9-4415-80f2-e43123d92cfb.png)

**Comment by anthonyraymond** [comment]
Torrent may also be sent to archive folder whenever it fails to announce 5 tiles in a row.

Maybe the .torrent file you have point toward an old tracker domain address that does not longer exist.
Can you try downloading the .torrent file from the tracker once again to replace the one you have already? And check if it disappear again?
